[package]
name = "ii-auth-plugin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ic-auth-plugin-types.workspace = true
serde_json.workspace = true
candid = "0.10.13"
ic-agent = "0.40.0"
