[package]
name = "pkcs11-ic-auth-plugin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.97"
ic-auth-plugin-types.workspace = true
ic-identity-hsm = "0.40.0"
serde_json = "1.0.140"
